mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from .views import QuestionCreateView, QuestionDetailView, QuestionListView, VoteView

app_name = 'polls'
urlpatterns = [
    path('', QuestionListView.as_view(), name='list'),
    path('new/', QuestionCreateView.as_view(), name='create'),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='detail'),
    path('vote/<int:pk>/', VoteView.as_view(), name='vote'),
]

polls/models.py
from model_utils.models import TimeStampedModel

from django.db import models


class Question(TimeStampedModel):
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text


class Choice(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

polls/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from .models import Choice, Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


ChoiceFormSet = inlineformset_factory(
    parent_model=Question, model=Choice, form=QuestionForm,
    extra=2, max_num=10, can_delete=False
)

polls/views.py
from rest_framework.generics import RetrieveAPIView
from rest_framework.response import Response

from django.contrib import messages
from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView

from .forms import ChoiceFormSet, QuestionForm
from .models import Choice, Question
from .serializers import ChoiceSerializer


class QuestionListView(ListView):
    queryset = Question.objects.all()
    context_object_name = 'questions'
    template_name = 'polls/list.html'

    def get_queryset(self):
        queryset = self.queryset.order_by('-id')
        return queryset


class QuestionDetailView(DetailView):
    model = Question
    context_object_name = 'question'
    template_name = 'polls/detail.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['choices'] = Choice.objects.filter(question_id=self.object.pk).order_by('pk')
        return data


class QuestionCreateView(CreateView):
    form_class = QuestionForm
    template_name = 'polls/form.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['choices'] = ChoiceFormSet(self.request.POST)
        else:
            data['choices'] = ChoiceFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        choices = context['choices']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if choices.is_valid():
                choices.instance = self.object
                choices.save()
        messages.success(self.request, 'Question is created.')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('polls:detail', kwargs={'pk': self.object.pk})


class VoteView(RetrieveAPIView):
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer

    def get(self, request, *args, **kwargs):
        choice = self.get_object()
        serializer = self.get_serializer(choice)
        choice.votes += 1
        choice.save()
        return Response(serializer.data)

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Polls</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="header">
        <h1><a href="/">Django Polls</a></h1>
    </div>

    <div class="container mt-3 questions">
        {% csrf_token %}
        <a class="btn btn-outline-primary" id="new" href="{% url 'polls:create' %}" data="New">New</a>
        {% block content %}
        {% endblock %}
    </div>

    <footer class="footer">
        <p>© jumpyoshim</p>
        <a href="https://jumpyoshim.hatenablog.com/about" target="_blank">About me</a>
        <a href="https://gitlab.com/jumpyoshim/django-polls" target="_blank">
            <i class="fab fa-gitlab gitlab"></i>
        </a>
        <a href="https://github.com/jumpyoshim/django-polls" target="_blank">
            <i class="fab fa-github github"></i>
        </a>
        <a href="https://twitter.com/jumpyoshim" target="_blank">
            <i class="fab fa-twitter twitter"></i>
        </a>
        <a href="https://www.facebook.com/jumpei.yoshimura.1" target="_blank">
            <i class="fab fa-facebook facebook"></i>
        </a>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    {% block extrajs %}{% endblock %}
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
<form method="post">
    <h2>Question</h2>
    <p class="question">「{{ question.text }}」</p>

    <h2>Choices</h2>
    {% for choice in choices %}
        <div class="choice">
            <span class="choice-text">「{{ choice.text }}」</span>
            <span class="votes" id="votes-{{ choice.pk }}">{{ choice.votes }}</span>

            {% csrf_token %}
            <button type="button" class="btn btn-outline-primary vote" id="{{ choice.pk }}">+1</button>
        </div>
    {% endfor %}
</form>
{% endblock %}

{% block extrajs %}
<script src="/static/js/polls.js"></script>
{% endblock %}

polls/templates/polls/form.html
{% extends 'polls/base.html' %}

{% block content %}
<form method="post">
    <h2>Question</h2>
    <p class="question">{{ form.as_table }}</p>

    <h2>Choices</h2>
    {{ choices.management_form }}
    <button type="button" class="btn btn-success" id="add">Add Choice</button>
    <div class="choice">
        <p>
            <label for="id_choice_set-0-text">Text:</label>
            <input type="text" name="choice_set-0-text" maxlength="200" id="id_choice_set-0-text" required>
        </p>
        <p>
            <label for="id_choice_set-1-text">Text:</label>
            <input type="text" name="choice_set-1-text" maxlength="200" id="id_choice_set-1-text" required>
        </p>
    </div>

    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

{% block extrajs %}
<script src="/static/js/polls.js"></script>
{% endblock %}

polls/templates/polls/list.html
{% extends 'polls/base.html' %}

{% block content %}
    <h2>Questions</h2>
    {% if questions %}
        <ul>
            {% for question in questions %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}